---

# Create artifactory ro/publish user
  - name: create user
    uri:
     url: "{{ art_url }}/{{ user_endpoint }}/{{ create_user_name }}"
     method: PUT
     user: "{{ admin_user_name }}"
     password: "{{ admin_api_key }}"
     body: >
       {
            "name" : "{{ create_user_name }}",
            "email" : "{{ create_user_email }}",
            "password" : "{{ create_user_pass }}",
            "admin" : "false",
            "profileUpdatable" : "true",
            "internalPasswordDisabled" : "false",
            "realm" : "Internal"
        }
     HEADER_Content-Type: "application/json"
     return_content: yes
     dest: "{{ ansible_env.HOME }}/{{ create_user_name }}-create.txt"
     force_basic_auth: yes
     status_code: 201
     body_format: json
    register: webpage
    
      
  - name: webpage response
    debug: var=webpage.content

