---  
# Delete ro/publish user
 - name: delete user
   uri:
    url: "{{ art_url }}/{{ user_endpoint }}/{{ delete_user_name }}"
    method: DELETE
    user: "{{ admin_user_name }}"
    password: "{{ admin_api_key }}"
    HEADER_Content-Type: "application/json"
    return_content: yes
    dest: "{{ ansible_env.HOME }}/{{ delete_user_name }}-delete.txt"
    force_basic_auth: yes
    status_code: 200
    body_format: json
   register: webpage
    
 - name: webpage response
   debug: var=webpage.content