---
  
# Delete permissions target
 - name: delete perms
   uri:
    url: "{{ art_url }}/{{ perms_endpoint }}/{{ target_name }}"
    method: DELETE
    user: "{{ admin_user_name }}"
    password: "{{ admin_api_key }}"
    HEADER_Content-Type: "application/json"
    return_content: yes
    dest: "{{ ansible_env.HOME }}/{{ target_name }}-delete.txt"
    force_basic_auth: yes
    status_code: 200
    body_format: json
   register: webpage
    
 - name: webpage response
   debug: var=webpage.content