---
# Delete artifactory local and virtual repositories
 - name: delete local/virtual repo
   uri:
    url: "{{ art_url }}/{{ repo_endpoint }}/{{ repo_key }}"
    method: DELETE
    user: "{{ admin_user_name }}"
    password: "{{ admin_api_key }}"
    HEADER_Content-Type: "application/json"
    return_content: yes
    dest: "{{ ansible_env.HOME }}/{{ repo_key }}-delete.txt"
    force_basic_auth: yes
    status_code: 200
    body_format: json
   register: webpage

 - name: webpage response
   debug: var=webpage.content


