---
# Create artifactory virtual repo
 - name: virtual repo
   uri:
    url: "{{ art_url }}/{{ repo_endpoint }}/{{ repo_key }}"
    method: PUT
    user: "{{ admin_user_name }}"
    password: "{{ admin_api_key }}"
    body: >
      {
        "key" : "{{ repo_key }}",
        "rclass" : "{{ virtual_repo_type }}",
        "packageType" : "{{ pkg_type }}",
        "repositories":  {{ sel_repo_list }},
        "description" : "",
        "notes" : "created by ansible playbook",
        "includesPattern" : "**/*",
        "excludesPattern" : "",
        "repoLayoutRef" : "{{ layout_type }}",
        "debianTrivialLayout" : false,
        "artifactoryRequestsCanRetrieveRemoteArtifacts": false,
        "pomRepositoryReferencesCleanupPolicy": "discard_active_reference",
        "defaultDeploymentRepo": "{{ sel_repo_key }}"
       }
    HEADER_Content-Type: "application/json"
    return_content: yes
    dest: "{{ ansible_env.HOME }}/{{ repo_key }}-create.txt"
    force_basic_auth: yes
    status_code: 200
    body_format: json
   register: webpage


 - name: webpage response
   debug: var=webpage.content
